name: NAW
favicon: null
layout_spectrum: 0.3638582492712885
typography_spectrum: 0.36742278770543635
title: Exploring the Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004a71'
    - '#1b1108'
    - '#009bd3'
    - '#a0dff0'
    - '#a83925'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.28805891261436045
purpose: []
